name: CPANPLUS
version: 0.077_01
abstract: Ameliorated interface to the CPAN
author: Jos Boumans <kane@cpan.org>
license: perl
distribution_type: module
no_index:
  directory:
    - lib/CPANPLUS/inc
    - inc
generated_by: Module::Install version 0.36
